FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG VITE_REACT_APP_REACT_BASE_URL=
ARG VITE_REACT_APP_BASE_URL=/
ARG VITE_REACT_APP_CONTAINERIZED_REACT_BASE_URL=

ENV VITE_REACT_APP_REACT_BASE_URL=${VITE_REACT_APP_REACT_BASE_URL} \
    VITE_REACT_APP_BASE_URL=${VITE_REACT_APP_BASE_URL} \
    VITE_REACT_APP_CONTAINERIZED_REACT_BASE_URL=${VITE_REACT_APP_CONTAINERIZED_REACT_BASE_URL}

RUN npm run build

FROM nginx:1.27-alpine AS runtime

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]