services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: project_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: test123456
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d project_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env.docker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"

  celery:
    build:
      context: ./backend
    container_name: celery
    command: celery -A celery_provider.celery_provider worker --loglevel=info
    env_file:
      - ./backend/.env.docker
    depends_on:
      backend:
        condition: service_started
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    container_name: frontend
    depends_on:
      backend:
        condition: service_started
    ports:
      - "80:80"

volumes:
  postgres-data:
  redis-data:
