"""Added a new table for tracking audits

Revision ID: 4a0e23f34675
Revises: 674156aafbf8
Create Date: 2026-03-11 06:44:32.242407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0e23f34675'
down_revision: Union[str, Sequence[str], None] = '674156aafbf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audits',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('old_quota', sa.Integer(), nullable=False),
    sa.Column('new_quota', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('change_owener_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audits')
    # ### end Alembic commands ###
