"""added month_to_date_usage as an actual model attr

Revision ID: 63fca8a29c19
Revises: b2603f5a571b
Create Date: 2026-03-10 23:06:31.831027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63fca8a29c19'
down_revision: Union[str, Sequence[str], None] = 'b2603f5a571b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tenants', sa.Column('month_to_date_usage', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tenants', 'month_to_date_usage')
    # ### end Alembic commands ###
