"""create users table

Revision ID: 7a89c017515f
Revises: 
Create Date: 2026-03-09 17:56:17.213129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a89c017515f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tenants', sa.Column('allow_overage', sa.Boolean(), nullable=False))
    op.alter_column('Tenants', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Tenants', 'monthly_quota',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('Useage_Events', sa.Column('status', sa.String(), nullable=False))
    op.alter_column('Useage_Events', 'token_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'Useage_Events', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Useage_Events', type_='unique')
    op.alter_column('Useage_Events', 'token_cost',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('Useage_Events', 'status')
    op.alter_column('Tenants', 'monthly_quota',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Tenants', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('Tenants', 'allow_overage')
    # ### end Alembic commands ###
