"""added prompt to model schema

Revision ID: b2603f5a571b
Revises: 7a89c017515f
Create Date: 2026-03-10 22:55:25.660787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2603f5a571b'
down_revision: Union[str, Sequence[str], None] = '7a89c017515f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Useage_Events', sa.Column('prompt', sa.String(), nullable=False))
    op.alter_column('Useage_Events', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Useage_Events', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('Useage_Events', 'prompt')
    # ### end Alembic commands ###
